lwa4p:
  ## joint_state_controller
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  ## position controller
  arm_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_4_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_5_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_6_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

